export const actionTypes = {
    LOADING_APPOINTMENTS:"LOADING_APPOINTMENTS",
    APPOINTMENTS_LOADED: "APPOINTMENTS_LOADED",
    OPEN_PATIENT_RECORD:"OPEN_PATIENT_RECORD",
    PATIENT_RECORD_OPENED:"PATIENT_RECORD_OPENED",
    PATIENT_INFO_CHANGED:"PATIENT_INFO_CHANGED",
    GENDERS_LOADED : "GENDERS_LOADED",
    INSURANCES_LOADED : "INSURANCES_LOADED",
    PATIENT_EDITED:"PATIENT_EDITED",
    CLEAR_MESSAGES:"CLEAR_MESSAGES",
    CLOSE_PATIENT_RECORD:"CLOSE_PATIENT_RECORD"
};